### ISSUE TITLE
検索結果をCSVへコピペしたい

### ISSUE THREAD

**Issue by MatsukageRyo** [skeiya/ProjectsTM#128]
【要望】
・稼働日ベースの工数をCSVへコピペしたい
・稼働日ベースの工数はxml上に表示されないため、検索結果一覧からコピペできるか、何かしらの形で一括出力したい

【内部事情】
・稼働日ベースの工数はUI側で毎回計算しているため、xml上には現れない。
・検索結果グリッドはクリップボードへのコピペに対応していたが、複数選択に対応しておらず、
　一括コピペできない実装になっている
　→　複数選択できるようにする解決策が最も簡単に見える。

**Comment by skeiya** [comment]
タスクリストの方に実装してもらった方がいいかも

**Comment by MatsukageRyo** [comment]
@skeiya  承知しました！

**Comment by MatsukageRyo** [comment]
@skeiya 
検索フォーム上項目のコピペを　PR＃127
タスクリスト上項目のコピペをPR＃135
に実装しました。
