### ISSUE TITLE
新規メンバーを追加した際に、全てのフィルターで表示されないようにする

### ISSUE THREAD

**Issue by MatsukageRyo** [skeiya/ProjectsTM#173]
現状
新規メンバーを追加する度に、全てのフィルターで非表示設定する運用がされている。

要望
新規メンバーを追加されても明示的に表示設定をしない限りは、表示されないようにしたい

**Comment by skeiya** [comment]
今のフィルター定義は「何を隠すか」という意味合いにしていましたが、「何を見せるか」という意味合いに変更したほうが適切だと思います。
