### ISSUE TITLE
ProjectsTMからプルできるメニューを追加する

### ISSUE THREAD

**Issue by MatsukageRyo** [skeiya/ProjectsTM#180]
リモートブランチに差分があると分かった後に、アプリ上からプルできるようにしたい

**Comment by skeiya** [comment]
私も同じようなことを考えていたのだけど、コンフリクトが発生するケースだと、かえって混乱しそうな気もする。
で、ローカルの変更がないときに限り、自動的にプルするようにするのがよさそうに思うのだけど、どうだろうか。

**Comment by MatsukageRyo** [comment]
@skeiya その案の方が良さそうです。ありがとうございます。
