### ISSUE TITLE
タスクグリッド上でマウスホイールの左右操作で左右にスクロールできるようにする。

### ISSUE THREAD

**Issue by skeiya** [skeiya/ProjectsTM#191]
すべてのマウスに備わっている機能ではないけど、できるタイプも多いので出来ると良さそう。

**Comment by naotoAkashi42** [comment]
Shift + スクロールなら実現できたのですがマウスの左右スクロールによってうまくスクロールをすることが
出来ません。実現するためのヒントを頂けないでしょうか？

MouseWheelイベント内でどうにかしてマウススクロールされた方向を検知することができればよいのですが。。。
今はお題とは違いますが↓のようにShift+垂直スクロールで水平スクロールするようにしています。
  private void GridControl_MouseWheel(object sender, MouseEventArgs e)
        {
            if (IsControlDown()) return;
            if (Math.Abs(e.Delta) < 120) return;
            if (ModifierKeys == Keys.Shift)
            {
                var maximumH = 1 + GetActualHScrollMaximum();
                var deltaH = -(e.Delta / 120) * hScrollBar.SmallChange * 2 * 10;
                var offsetH = Math.Min(Math.Max(hScrollBar.Value + deltaH, vScrollBar.Minimum), maximumH);
                hScrollBar.Value = offsetH;
                return ;
            }
            var maximumV = 1 + GetActualVScrollMaximum();
            var deltaV = -(e.Delta / 120) * vScrollBar.SmallChange * 2 * 10;
            var offsetV = Math.Min(Math.Max(vScrollBar.Value + deltaV, vScrollBar.Minimum), maximumV);
            vScrollBar.Value = offsetV;
        }

いろいろ調べてみると
WndProcをオーバーライドする、みたいなことはあったのですが検出しかできないように思えました。

**Comment by skeiya** [comment]
これ難しそうですね。大変な割にそこまで使わなそう。やめときましょう。

**Comment by naotoAkashi42** [comment]
わかりました。ありがとうございます。
もう少し調べて簡単なやり方なかったらやめておきます。

あと、
色々調べてたらShift+スクロールで横スクロールに対応しているアプリは結構あったような気がしたので
それだけでも入れたらどうかと思うのですがいかがでしょうか？

**Comment by skeiya** [comment]
自分がやらないので知らなかったです。一般的な操作感として使う人がいそうなら対応するのも良いと思いますよ。

**Comment by naotoAkashi42** [comment]
わかりました！ありがとうございます！
