### ISSUE TITLE
タスクリストに、旧検索の”簡易指定”機能を移植する。

### ISSUE THREAD

**Issue by skeiya** [skeiya/ProjectsTM#194]

**Comment by naotoAkashi42** [comment]
修正に当たって下記現象の解決策がなく、困っています。もし解決策をご存知でしたら教えていただけますでしょうか？

**TaskListFormのデザイナーのビルドが走ると勝手にユーザーコントール(TaskListGrid)が勝手に消える。**

一回UIに修正を入れた時点でTaskListGridが消え、その時はBuildは通るのですが次UIに手を入れるとBuildが通らなくなります。

**Comment by skeiya** [comment]
私もたまーーにその現象に出くわすけど、根本解決できたことが無い。。。
勝手に削除されたところを手編集で元に戻す、という場当たり対応をしています。
↓ここにも同じ現象が上がってますね。
https://stackoverflow.com/questions/2677646/how-do-i-keep-visual-studios-windows-forms-designer-from-deleting-controls

**Comment by naotoAkashi42** [comment]
ありがとうございます。

ただ手編集で戻そうとするとデザイナのビルドが走るのかなんなのか、そのタイミングでオブジェクト参照がnullに
なって例外になってしまいます。

このケースの対策はあるのでしょうか？
(プロパティであればnull check入れようと思ったのですがループの中で例外が出ていました。)

**Comment by skeiya** [comment]
ちゃんとわかってないけど、
デザイナが問題なのであれば、VisualStudioを閉じて、テキストエディタで編集すれば回避できるはずだと思います。

**Comment by naotoAkashi42** [comment]
ありがとうございます！試してみます。
