### ISSUE TITLE
ManagementWokingDaysFormのリファクタリング

### ISSUE THREAD

**Issue by y-ono13** [skeiya/ProjectsTM#278]
- `ManagementWokingDaysForm`が直接ViewDataを書き換えるのをやめる。
- コピーされたコレクション`IEnumerable<CallenderDay>`を参照するようにする。
- 追加/削除操作はコールバック関数でコレクションを投げてコールバック関数内で`ViewData`を書き換える。
- `_workItems`を無くす。`_workItems`を使って行っている「日付を削除可能かどうか」という判定を、コールバック関数内で行うようにする。
- 同じ日付が登録可能になっているのを直す(`Enumerable.Distinct()`を使うこと)。

**Comment by MatsukageRyo** [comment]
@y-ono13 
レビューお願い致します
→ ManagementWokingDaysFormのリファクタリング #280
