### ISSUE TITLE
作業項目のドラッグ＆ドロップの際に、非選択の項目をいきなり操作できるようにする。

### ISSUE THREAD

**Issue by skeiya** [skeiya/ProjectsTM#287]
従来は、一度選択してから、改めてD&Dしないと操作できない。

**Comment by MatsukageRyo** [comment]
@skeiya 
非選択の項目をD＆Dできているように見えており、手元で再現していません。
何か再現させる条件がありますか？

**Comment by skeiya** [comment]
確かに、まっさらな状態からだとD&Dできました。
できないのは、一度選択してESCキー押下等で選択解除してから、同じものをD&Dしようとした場合でした。
